### ISSUE TITLE
creating a new ScenarioReport from a hash gives an error about name:

### ISSUE THREAD

**Issue by TK-23** [urbanopt/urbanopt-scenario-gem#29] opened 2019-07-23 18:09 UTC
URBANopt::Scenario::DefaultReports::ScenarioReport.new(scenario_reports_json)
NoMethodError: undefined method `name' for #<Hash:0x007f97c18015a0>

**Comment by macumber** [comment] 2019-07-24 22:25
Duplicate of https://github.com/urbanopt/urbanopt-scenario-gem/issues/30

**Closed by macumber** 2019-07-24 22:25 UTC
